
default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost
  # port: 5432
  # username: postgres
  # password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_api_development

  
test:
  <<: *default
  database: blog_api_test


production:
  <<: *default
  database: blog_api_production
  username: blog_api
  password: <%= ENV['BLOG_API_DATABASE_PASSWORD'] %>
